- hosts: localhost
  gather_facts: no
  vars_files:
    - /home/ansible/env_vars.yml
  tasks:
    - name: Create AWS key pair using Ansible's key.
      local_action: ec2_key
      args:
        name: ansible_keypair
        key_material: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"

    - name: Provision instances
      local_action: ec2
      args:
        instance_type: t2.micro
        group: "{{ SEC_GROUP_NAME }}"
        keypair: ansible_keypair
        image: "{{ AMI_ID }}"
        assign_public_ip: yes
        vpc_subnet_id: "{{ DEFAULT_VPC_SUBNET }}"
        wait: yes
        instance_tags:
          type: web
        count: 1
      register: ec2

    - name: Add host to inventory
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: webservers
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        ansible_ssh_private_key_file: /home/ansible/.ssh/id_rsa
      loop: "{{ ec2.instances }}"

    - name: Create S3 Bucket
      local_action: aws_s3
      args:
        bucket: "{{ BUCKET_NAME }}"
        mode: create
        permission: public-read

    - name: Add file to bucket
      local_action: aws_s3
      args:
        bucket: "{{ BUCKET_NAME }}"
        mode: put
        object: /webimage.png
        src: /home/ansible/webimage.png
        permission: public-read

- hosts: localhost
  gather_facts: no
  vars_files:
    - /home/ansible/env_vars.yml
  tasks:
    - name: Create AWS key pair using Ansible's key.
      local_action: ec2_key
      args:
        name: ansible_keypair
        key_material: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"

    - name: Provision instances
      local_action: ec2
      args:
        instance_type: t2.micro
        group: "{{ SEC_GROUP_NAME }}"
        keypair: ansible_keypair
        image: "{{ AMI_ID }}"
        assign_public_ip: yes
        vpc_subnet_id: "{{ DEFAULT_VPC_SUBNET }}"
        wait: yes
        instance_tags:
          type: web
        count: 1
      register: ec2

    - name: Add host to inventory
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: webservers
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        ansible_ssh_private_key_file: /home/ansible/.ssh/id_rsa
      loop: "{{ ec2.instances }}"

    - name: Create S3 Bucket
      local_action: aws_s3
      args:
        bucket: "{{ BUCKET_NAME }}"
        mode: create
        permission: public-read

    - name: Add file to bucket
      local_action: aws_s3
      args:
        bucket: "{{ BUCKET_NAME }}"
        mode: put
        object: /webimage.png
        src: /home/ansible/webimage.png
        permission: public-read
